language: cpp

os:
  - linux
  - osx

# Use the most recent stable XCode image according to the table posted
# in the Travis CI documentation.
#
# https://docs.travis-ci.com/user/reference/osx/
osx_image: xcode11

env:
  global:
    - MAKEFLAGS="-j 2"

sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev

compiler:
  - clang
  - gcc

# Let us install a set of Homebrew packages for Mac OS X. This appears
# to be rather clunky, but the official documentation contains similar
# examples.
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                                    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions boost && brew upgrade boost || brew install boost; fi

script:
  - mkdir build
  - cd build
  - cmake ../code/cpp/
  - make
  - make test
  - ./s3m -q -i ../data/example/synthetic.csv -m 15 -o synthetic.json
