#!/usr/bin/env python3

import json
import sys

with open(sys.argv[1]) as f:
    data = json.load(f)

########################################################################
# Generate shapelet pairs
########################################################################
#
# Candidates are generated by ensuring that one shapelet precedes
# the other _and_ they are coming from the same time series.

shapelets = data['shapelets']
pairs     = []

for s in shapelets:
    i   = s['index']
    p_i = s['start']
    for t in shapelets:
        j   = t['index']
        p_j = t['start']

        if i == j and p_i < p_j:
            pairs.append((s,t))

print("There are {} shapelet pair candidates".format(len(pairs)))
